include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - bloc
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    unused_import: warning
    dead_code: warning
    missing_return: error

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_classes_with_only_static_members: true
    use_super_parameters: true
    sort_constructors_first: true
    unnecessary_this: true
    require_trailing_commas: true
    camel_case_types: true
    file_names: true
    library_prefixes: true
    prefer_final_locals: true
    prefer_final_fields: true
    avoid_unnecessary_containers: true
    avoid_returning_null: true
    avoid_empty_else: true
    curly_braces_in_flow_control_structures: true

bloc_lint:
  rules:
    - close_streams
    - use_valid_bloc_state_names
    - prefer_valid_bloc_event_names
    - avoid_positional_boolean_parameters
    - avoid_public_notifier_properties